---
  # Security Enhanced Linux configuration

- name: Install required dependencies
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - libselinux-python
    - libsemanage-python

- name: Enable SELinux
  block:
    - name: Enable selinux
      selinux:
        policy: targeted
        state: enforcing

    - name: install selinux-policy-targeted
      yum:
        name: selinux-policy-targeted
        state: latest

    - name: install SEManage
      yum:
        name: policycoreutils-python
        state: latest

  when: sel_disable == false

- name: Disable SELinux
  selinux:
    state: disabled
  when: sel_disable == true

- include_tasks: restart.yml
