---
  # Security Enhanced Linux configuration

- name: Install required dependencies
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - libselinux-python
    - libsemanage-python

- name: Enable SELinux
  block:
    - name: Enable selinux
      selinux:
        policy: targeted
        state: enforcing

    - name: install selinux-policy-targeted
      yum:
        name: selinux-policy-targeted
        state: latest

    - name: install SEManage
      yum:
        name: policycoreutils-python
        state: latest

  tags:
    - deploy
    - selinux

- name: Disable SELinux
  selinux:
    state: disabled
  tags:
    - deploy

- name: restart the server
  import_tasks: restart.yml
  tags:
    - restart
    - deploy
