---
  # Security Enhanced Linux configuration

- name: Install required dependencies - CentOS
  yum:
    name:
      - libselinux-python
      - libsemanage-python
      - selinux-policy-targeted
      - policycoreutils-python
    state: latest
  when: ansible_distribution == 'CentOS'

- name: Install required dependencies - Fedora
  dnf:
    name:
      - libselinux-python
      - libsemanage-python
      - selinux-policy-targeted
      - policycoreutils-python
    state: latest
  when: ansible_distribution == 'Fedora'

- name: Enable selinux
  selinux:
    policy: targeted
    state: enforcing
  tags:
    - selinux-enable

- name: Disable SELinux
  selinux:
    state: disabled
  tags:
    - selinux-disable
    - deploy

- name: restart the server
  import_tasks: restart.yml
  tags:
    - restart
    - deploy
